from . import patient
from . import doctor
from . import department
from . import appointment
from . import medical_record
from . import prescription
from . import lab_test
from . import observation
from . import radiology_test
from . import bed
from . import admission
from . import drug
from . import invoice
from . import location
from . import concept
from . import procedure
