{
    'name': 'Hospital Management',
    'version': '1.0',
    'summary': 'Full Hospital Management System',
    'description': 'Comprehensive hospital management system including patient registration, appointments, medical records, pharmacy, lab, and billing - similar to Bahmni',
    'category': 'Healthcare',
    'author': 'Taye Animaw',
    'depends': ['base', 'mail', 'calendar', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'views/patient_view.xml',
        'views/doctor_view.xml',
        'views/appointment_view.xml',
        'views/medical_record_view.xml',
        'views/prescription_view.xml',
        'views/lab_test_view.xml',
        'views/department_view.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}
