{
    'name': ' Taye Hospital System',
    'version': '1.0',
    'summary': 'Full Hospital Management System',
    'category': 'Healthcare',
    'author': 'Taye Animaw',
    'depends': ['base', 'mail', 'calendar', 'account', 'website'],
    'data': [
        'data/sequences.xml',
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/patient_view.xml',
        'views/doctor_view.xml',
        'views/appointment_view.xml',
        'views/medical_record_view.xml',
        'views/prescription_view.xml',
        'views/lab_test_view.xml',
        'views/radiology_test_view.xml',
        'views/department_view.xml',
        'views/observation_view.xml',
        'views/location_view.xml',
        'views/concept_view.xml',
        'views/procedure_view.xml',
        'views/program_view.xml',
        'views/bed_view.xml',
        'views/admission_view.xml',
        'views/drug_view.xml',
        'views/invoice_view.xml',
        'views/menu.xml',
        'views/website_templates.xml',
        'reports/patient_report.xml',
    ],
    'description': 'Complete Hospital Management System replicating all Bahmni features: patient registration with relationships and allergies, clinical workflows with observations and diagnoses (ICD codes), orders (lab, radiology, procedures), pharmacy with inventory, inpatient management with beds and admissions, billing, appointments with slots, queue management, locations, concepts, programs, telemedicine, operation theater, discharge summaries, patient documents, comprehensive reports, and Bahmni Apps-style dashboard.',
    'installable': True,
    'application': True,
}
